# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 611499d7a28cfd99d657aee10b1807cce90af14292feb43b5fc1f97c69166b0262a0da9a6ddc3cad8fcab6f00886fa40823037a4dee3c924371d45a3a4f7f9f5

test:
  secret_key_base: 1eeab04601896f3f3f3c3bf627a84ee0773e60ff33edc97b39e6a329a622f478187bc1e170359b1e281369558875c8e48c65d41b97b33a3e14b98085d4a4fd9e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
